import "../styles/globals.css";

import Footer from "../components/footer/Footer";
import Header from "@/components/header/Header";
import Promosale from "@/components/header/promoSale/Promosale";
import NavbarSection from "@/components/header/navbar/CustomNavbar";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="h-screen relative">
        <Promosale />
        <Header />
        <NavbarSection />
        {children}
        <Footer />
      </body>
    </html>
  );
}
